import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ne';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    feed: 'Feed',
    report: 'Report',
    getStarted: 'Get Started',
    heroTitle: "I'm civic",
    heroSubtitle: 'REPORTER',
    letsReport: "Let's Report",
    allYour: 'ALL YOUR',
    civicNeeds: 'civic needs',
    reportTitle1: 'ALL',
    reportTitle2: 'YOUR report',
    fileAReport: 'File a Report',
    recentReports: 'Recent Reports',
    viewFeed: 'View Feed',
    guidelines: 'Guidelines',
    beSpecific: 'Be Specific',
    beSpecificDesc: 'Clearly describe the issue and its exact location.',
    provideEvidence: 'Provide Evidence',
    provideEvidenceDesc: 'Upload clear photos or videos of the problem.',
    stayUpdated: 'Stay Updated',
    stayUpdatedDesc: "Follow your report's progress in the community feed.",
    issueTitle: 'Issue Title',
    category: 'Category',
    location: 'Location',
    description: 'Description',
    evidence: 'Evidence (Photo/Video)',
    submitReport: 'Submit Report',
    success: 'SUCCESS',
    dhanyabaad: 'Dhanyabaad! 🙏',
    successDesc: 'Your report has been successfully recorded and forwarded to the relevant authorities for immediate action.',
    share: 'Share',
    referenceId: 'Reference ID',
    garbage: 'Garbage / Waste',
    road: 'Road Damage',
    water: 'Water Supply',
    electricity: 'Electricity',
    titlePlaceholder: 'e.g., Large pothole on main road',
    locationPlaceholder: 'e.g., Koteshwor, Kathmandu',
    descPlaceholder: 'Provide more details about the issue...',
    changeFile: 'Change File',
    uploadMedia: 'Upload Media',
    dragDrop: 'Drag and drop or click to browse',
    privacy: 'Privacy',
    terms: 'Terms',
    contact: 'Contact',
    builtForNepal: 'Built for a better Nepal.',
    allTypesDesc: 'All types of reports in one place with the assurance of highest accountability.',
    garbagePill: 'Garbage Collection',
    roadPill: 'Road Repair',
    waterPill: 'Water Supply',
    electricityPill: 'Electricity',
    safetyPill: 'Public Safety',
    infraPill: 'Infrastructure',
    envPill: 'Environment',
    rightsPill: 'Civic Rights',
    govPill: 'Local Governance',
    sanitationPill: 'Sanitation',
    publicFeed: 'Public Feed',
    feedDesc: 'Real-time reports from citizens across Nepal.',
    allCategories: 'All Categories',
    noReports: 'No reports found in this category.',
    loadingReports: 'Loading reports...',
    aboutUs: 'About Us',
    mission: 'Our Mission',
    missionDesc: 'Empowering every citizen of Nepal with a voice to report local issues and hold authorities accountable.',
    vision: 'Our Vision',
    visionDesc: 'A transparent Nepal where infrastructure and services are maintained through active civic participation.',
    theStory: 'The Story',
    storyDesc: 'ComplaineNepal was born out of the need for a direct, transparent channel between the people and those responsible for public services. We believe that technology can bridge the gap of accountability.',
    whoWeAre: 'Who We Are',
    teamDesc: 'We are a small but passionate team of teenagers from Nepal, dedicated to leveraging technology for civic accountability.',
    yunishBhatta: 'Yunish Bhatta',
    aasisBagale: 'Aasis Bagale',
    coFounder: 'Your Friend',
    offgridhqTitle: 'OffgridHQ',
    offgridhqDesc: 'This platform is built and maintained by OffgridHQ—not a corporation or a company, but a group of teenage friends from Nepal making things and driving civic change through code.',
    visitOffgrid: 'Discover OffgridHQ',
    communityFeed: 'Community Feed',
    whatsOnYourMind: "What's on your mind?",
    trending: 'Trending',
    remark: 'Remark',
    remarks: 'Remarks',
    postRemark: 'Post Remark',
    noRemarks: 'No citizen remarks yet',
    addRemarkPlaceholder: 'Add a remark...',
    openFullArchives: 'Open Full Archives',
    bridgingGap: 'Bridging the gap between citizens & accountability',
    rightsReserved: 'ALL RIGHTS RESERVED.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    citizen: 'Citizen',
    backToArchives: 'Back to Archives',
    reportIdLabel: 'Report #',
    showMore: 'Show More',
    showLess: 'Show Less',
    discussionRecords: 'Discussion records',
    verificationRemark: 'Enter verification remark...',
    verifyPost: 'Verify & Post',
    caseNotAccessible: 'Case Not Accessible',
    backToFeed: 'Back to Feed',
    retrievingRecord: 'Retrieving Record',
    profile: 'Profile',
    connectWithUs: 'Connect with us',
  },
  ne: {
    home: 'गृहपृष्ठ',
    feed: 'फिड',
    report: 'रिपोर्ट',
    getStarted: 'सुरु गर्नुहोस्',
    heroTitle: 'म नागरिक',
    heroSubtitle: 'रिपोर्टर',
    letsReport: 'रिपोर्ट',
    allYour: 'तपाईंका सबै',
    civicNeeds: 'नागरिक आवश्यकताहरू',
    reportTitle1: 'तपाईंका',
    reportTitle2: 'सबै रिपोर्ट',
    fileAReport: 'रिपोर्ट दर्ता गर्नुहोस्',
    recentReports: 'हालैका रिपोर्टहरू',
    viewFeed: 'फिड हेर्नुहोस्',
    guidelines: 'निर्देशिकाहरू',
    beSpecific: 'विशिष्ट हुनुहोस्',
    beSpecificDesc: 'मुद्दा र यसको सही स्थान स्पष्ट रूपमा वर्णन गर्नुहोस्।',
    provideEvidence: 'प्रमाण दिनुहोस्',
    provideEvidenceDesc: 'समस्याको स्पष्ट फोटो वा भिडियोहरू अपलोड गर्नुहोस्।',
    stayUpdated: 'अपडेट रहनुहोस्',
    stayUpdatedDesc: 'सामुदायिक फिडमा आफ्नो रिपोर्टको प्रगति पछ्याउनुहोस्।',
    issueTitle: 'मुद्दाको शीर्षक',
    category: 'वर्ग',
    location: 'स्थान',
    description: 'विवरण',
    evidence: 'प्रमाण (फोटो/भिडियो)',
    submitReport: 'रिपोर्ट बुझाउनुहोस्',
    success: 'सफल',
    dhanyabaad: 'धन्यवाद! 🙏',
    successDesc: 'तपाईंको रिपोर्ट सफलतापूर्वक रेकर्ड गरिएको छ र तत्काल कारबाहीका लागि सम्बन्धित निकायमा पठाइएको छ।',
    share: 'साझा गर्नुहोस्',
    referenceId: 'सन्दर्भ आईडी',
    garbage: 'फोहोर / मैला',
    road: 'सडक क्षति',
    water: 'खानेपानी आपूर्ति',
    electricity: 'विद्युत',
    titlePlaceholder: 'जस्तै: मुख्य सडकमा ठूलो खाल्डो',
    locationPlaceholder: 'जस्तै: कोटेश्वर, काठमाडौं',
    descPlaceholder: 'मुद्दाको बारेमा थप विवरण दिनुहोस्...',
    changeFile: 'फाइल परिवर्तन गर्नुहोस्',
    uploadMedia: 'मिडिया अपलोड गर्नुहोस्',
    dragDrop: 'तान्नुहोस् र छोड्नुहोस् वा ब्राउज गर्न क्लिक गर्नुहोस्',
    privacy: 'गोपनीयता',
    terms: 'सर्तहरू',
    contact: 'सम्पर्क',
    builtForNepal: 'राम्रो नेपालको लागि निर्माण गरिएको।',
    allTypesDesc: 'उच्च जवाफदेहिताको आश्वासनका साथ सबै प्रकारका रिपोर्टहरू एकै ठाउँमा।',
    garbagePill: 'फोहोर संकलन',
    roadPill: 'सडक मर्मत',
    waterPill: 'खानेपानी',
    electricityPill: 'विद्युत',
    safetyPill: 'जनसुरक्षा',
    infraPill: 'पूर्वाधार',
    envPill: 'वातावरण',
    rightsPill: 'नागरिक अधिकार',
    govPill: 'स्थानीय शासन',
    sanitationPill: 'सरसफाई',
    publicFeed: 'सार्वजनिक फिड',
    feedDesc: 'नेपालभरका नागरिकहरूबाट वास्तविक समयका रिपोर्टहरू।',
    allCategories: 'सबै वर्गहरू',
    noReports: 'यस वर्गमा कुनै रिपोर्ट फेला परेन।',
    loadingReports: 'रिपोर्टहरू लोड हुँदैछ...',
    aboutUs: 'हाम्रो बारेमा',
    mission: 'हाम्रो उद्देश्य',
    missionDesc: 'नेपालका प्रत्येक नागरिकलाई स्थानीय मुद्दाहरू रिपोर्ट गर्न र अधिकारीहरूलाई जवाफदेही बनाउन आवाज सशक्त बनाउने।',
    vision: 'हाम्रो दृष्टिकोण',
    visionDesc: 'एक पारदर्शी नेपाल जहाँ सक्रिय नागरिक सहभागिता मार्फत पूर्वाधार र सेवाहरू कायम राखिन्छ।',
    theStory: 'कथा',
    storyDesc: 'कम्प्लेननेपाल जनता र सार्वजनिक सेवाका लागि जिम्मेवार व्यक्तिहरू बीचको प्रत्यक्ष, पारदर्शी च्यानलको आवश्यकताबाट जन्मिएको हो। हाम्रो विश्वास छ कि प्रविधिले जवाफदेहिताको खाडललाई कम गर्न सक्छ।',
    whoWeAre: 'हाम्रो टोली',
    teamDesc: 'हामी नेपालका किशोरकिशोरीहरूको सानो तर भावुक टोली हौं, जो नागरिक जवाफदेहिताका लागि प्रविधिको प्रयोग गर्न समर्पित छौं।',
    yunishBhatta: 'युनीश भट्ट',
    aasisBagale: 'आशिश बगाले',
    coFounder: 'तपाईंको साथी',
    offgridhqTitle: 'OffgridHQ',
    offgridhqDesc: 'यो प्लेटफर्म OffgridHQ द्वारा निर्मित र सञ्चालित हो—कुनै कर्पोरेसन वा कम्पनी होइन, तर कोड मार्फत नागरिक परिवर्तन ल्याउन र राम्रा चीजहरू बनाउन लागिपरेका नेपालका किशोर साथीहरूको समूह।',
    visitOffgrid: 'OffgridHQ हेर्नुहोस्',
    communityFeed: 'सामुदायिक फिड',
    whatsOnYourMind: 'तपाईंको विचार के छ?',
    trending: 'ट्रेन्डिङ',
    remark: 'प्रतिक्रिया',
    remarks: 'प्रतिक्रियाहरू',
    postRemark: 'प्रतिक्रिया पठाउनुहोस्',
    noRemarks: 'कुनै प्रतिक्रिया छैन',
    addRemarkPlaceholder: 'प्रतिक्रिया लेख्नुहोस्...',
    openFullArchives: 'पूर्ण रेकर्डहरू हेर्नुहोस्',
    bridgingGap: 'नागरिक र जवाफदेहिता बीचको दुरी कम गर्दै',
    rightsReserved: 'सबै अधिकार सुरक्षित।',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवाका सर्तहरू',
    citizen: 'नागरिक',
    backToArchives: 'अभिलेखमा फर्कनुहोस्',
    reportIdLabel: 'रिपोर्ट नं.',
    showMore: 'थप हेर्नुहोस्',
    showLess: 'कम हेर्नुहोस्',
    discussionRecords: 'छलफल रेकर्डहरू',
    verificationRemark: 'प्रमाणीकरण प्रतिक्रिया लेख्नुहोस्...',
    verifyPost: 'प्रमाणित गर्नुहोस् र पठाउनुहोस्',
    caseNotAccessible: 'केस उपलब्ध छैन',
    backToFeed: 'फिडमा फर्कनुहोस्',
    retrievingRecord: 'रेकर्ड लोड हुँदैछ',
    profile: 'प्रोफाइल',
    connectWithUs: 'हामीसँग जोडिनुहोस्',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
